{% set name = "libxcrypt" %}
{% set version = "4.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/besser82/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 71513a31c01a428bccd5367a32fd95f115d6dac50fb5b60c779d5c7942aec071

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # The ABI is very stable
    - {{ pin_subpackage('libxcrypt', max_pin=None) }}
  script_env:
    - OBSOLETE_API=no

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - pkg-config
    - perl

test:
  commands:
    - echo $(ls "$PREFIX/include") && test -f "${PREFIX}/include/crypt.h"
    - test -f "${PREFIX}/lib/libcrypt${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/pkgconfig/libxcrypt.pc"


about:
  home: https://github.com/besser82/libxcrypt
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING.LIB
    - LICENSING
  summary: Extended crypt library for descrypt, md5crypt, bcrypt, and others
  description: Extended crypt library for descrypt, md5crypt, bcrypt, and others
  doc_url: https://github.com/besser82/libxcrypt
  dev_url: https://github.com/besser82/libxcrypt

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/47182
    reason: Dependency for systemd
  recipe-maintainers:
    - ianaobi
    - bkreider
    - chrisburr
    - mbargull
